language: generic
sudu: required
services: 
  - docker

before_install:
  - docker build -t gfehrk2a/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true gfehrk2a/docker-react npm run test

# deploy:
#   provider: elasticbeanstalk
#   region: "us-east-1"
#   app: "docker"
#   env: "Docker-env"
#   bucket_name: "s3 bucket name"
#   bucket_path: "docker"
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key:
#     secure: "$AWS_SECRET_KEY"
